## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
# - osx
  - linux
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly

addons:
  apt: # apt-get for linux
    sources:
      - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - cmake
    - libboost-all-dev
    - build-essential
    - zlib1g-dev
    - libsdl2-dev
    - libjpeg-dev
    - nasm
    - tar
    - libbz2-dev
    - libgtk2.0-dev
    - git
    - libfluidsynth-dev
    - libgme-dev
    - libopenal-dev
    - timidity
    - libwildmidi-dev
    - unzip

env:
  - CC=gcc-4.9 && CXX=g++-4.9
## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("ReinforcementLearningEnvironmentVizDoom"); Pkg.test("ReinforcementLearningEnvironmentVizDoom"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("ReinforcementLearningEnvironmentVizDoom")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("ReinforcementLearningEnvironmentVizDoom")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
