## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 0.7
  - nightly
notifications:
  email: false
git:
  depth: 99999999

addons:
  apt: # apt-get for linux
    packages:
    - cmake
    - build-essential
    - zlib1g-dev
    - libsdl2-dev
    - libjpeg-dev
    - nasm
    - tar
    - libbz2-dev
    - libgtk2.0-dev
    - git
    - libfluidsynth-dev
    - libgme-dev
    - libopenal-dev
    - timidity
    - libwildmidi-dev
    - unzip

# before_script: # homebrew for mac
#   - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

script:
  - julia -e 'using Pkg; Pkg.add(pwd()); Pkg.build("RLEnvVizDoom");'